# Generated by Django 2.0.9 on 2018-10-18 00:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualCanvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Canvas Title')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Compliant Title')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='Start Time of Public Canvas Editing')),
                ('end_time', models.DateTimeField(verbose_name='Time the Canvas Will Stop Accepting Edits')),
                ('grid_length', models.PositiveSmallIntegerField(blank=True, default=8, null=True, verbose_name='Torus grid length, where max number of cells is this squared. If null, cells will spread ')),
                ('cell_divisions', models.PositiveSmallIntegerField(default=8, verbose_name='Cell Divisions')),
                ('is_torus', models.BooleanField(verbose_name="Initialize a torus grid that can't be changed")),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Person who created this VisualCanvas')),
            ],
        ),
        migrations.CreateModel(
            name='VisualCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_position', models.IntegerField()),
                ('x_position', models.IntegerField()),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Artist for this Part of the Canvas')),
            ],
        ),
        migrations.CreateModel(
            name='VisualCellEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('edges_horizontal', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('edges_vertical', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('edges_south_east', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('edges_south_west', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.VisualCell')),
            ],
        ),
    ]
