# Generated by Django 2.0.9 on 2018-12-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualcelledit',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterOrderWithRespectTo(
            name='visualcelledit',
            order_with_respect_to='cell',
        ),
    ]
