# Generated by Django 2.0.9 on 2018-10-24 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualcell',
            name='canvas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='visual_cells', to='visual.VisualCanvas', verbose_name='Canvas Cell is Associated With'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visualcanvas',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Person who created this Visual Canvas'),
        ),
        migrations.AlterField(
            model_name='visualcanvas',
            name='grid_length',
            field=models.PositiveSmallIntegerField(blank=True, default=8, null=True, verbose_name='Torus grid length, where max number of cells is this squared. If null, cells will spread.'),
        ),
        migrations.AlterField(
            model_name='visualcell',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_cells', to=settings.AUTH_USER_MODEL, verbose_name='Artist for this Part of the Canvas'),
        ),
    ]
