# Generated by Django 2.0.9 on 2018-10-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_auto_20181024_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualcelledit',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_edits', to='visual.VisualCell'),
        ),
    ]
