# Generated by Django 2.0.9 on 2018-12-29 03:19

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0003_auto_20181227_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualcanvas',
            name='cell_divisions',
        ),
        migrations.AddField(
            model_name='visualcanvas',
            name='cell_height',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Height of cell grid (defaults to 8x8 grid)'),
        ),
        migrations.AddField(
            model_name='visualcanvas',
            name='cell_width',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Width of cell grid (defaults to 8x8 grid)'),
        ),
        migrations.AddField(
            model_name='visualcelledit',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Whether the edit is valid and included in time series'),
        ),
        migrations.AlterField(
            model_name='visualcanvas',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visualcell',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visualcelledit',
            name='edges_horizontal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), db_column='x', size=None),
        ),
        migrations.AlterField(
            model_name='visualcelledit',
            name='edges_south_east',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), db_column='z', size=None),
        ),
        migrations.AlterField(
            model_name='visualcelledit',
            name='edges_south_west',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), db_column='t', size=None),
        ),
        migrations.AlterField(
            model_name='visualcelledit',
            name='edges_vertical',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), db_column='y', size=None),
        ),
    ]
