# Generated by Django 2.0.9 on 2018-10-30 23:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visual', '0003_auto_20181024_0127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visualcell',
            unique_together={('canvas', 'x_position', 'y_position'), ('canvas', 'artist')},
        ),
    ]
