# Generated by Django 2.0.9 on 2018-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_auto_20181030_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualcanvas',
            name='grid_width',
            field=models.PositiveSmallIntegerField(blank=True, default=8, null=True, verbose_name='Torus grid width, where max number of cells is this squared. If null, cells will spread randomly.'),
        ),
        migrations.AddField(
            model_name='visualcanvas',
            name='new_cells_allowed',
            field=models.BooleanField(default=False, verbose_name='Allow new cells to be added'),
        ),
        migrations.AddField(
            model_name='visualcell',
            name='is_editable',
            field=models.BooleanField(default=True, verbose_name='Whether artists are allowed to edit this cell.'),
        ),
        migrations.AlterField(
            model_name='visualcanvas',
            name='grid_length',
            field=models.PositiveSmallIntegerField(blank=True, default=8, null=True, verbose_name='Torus grid length, where max number of cells is this squared. If null, cells will spread randomly.'),
        ),
        migrations.AlterField(
            model_name='visualcell',
            name='x_position',
            field=models.IntegerField(verbose_name='Horizontal position relative to 0'),
        ),
        migrations.AlterField(
            model_name='visualcell',
            name='y_position',
            field=models.IntegerField(verbose_name='Veritical position relative to 0'),
        ),
    ]
