# Generated by Django 2.0.9 on 2018-12-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_auto_20181231_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualcell',
            name='height',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Height of cell grid (defaults to 8x8 grid)'),
        ),
        migrations.AddField(
            model_name='visualcell',
            name='width',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Width of cell grid (defaults to 8x8 grid)'),
        ),
    ]
