# Generated by Django 2.0.9 on 2018-11-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_auto_20181105_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualcanvas',
            name='grid_length',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Torus grid length, where max number of cells is this squared. If null, cells will spread randomly.'),
        ),
        migrations.AlterField(
            model_name='visualcanvas',
            name='grid_width',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Torus grid width, where max number of cells is this squared. If null, cells will spread randomly.'),
        ),
        migrations.AlterField(
            model_name='visualcanvas',
            name='is_torus',
            field=models.BooleanField(default=False, verbose_name="Initialize a torus grid that can't be changed"),
        ),
    ]
