# Generated by Django 2.0.9 on 2018-11-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0006_auto_20181105_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualcanvas',
            name='grid_length',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Grid vertical (y) length, where max number of cells is this time grid_width.'),
        ),
        migrations.AlterField(
            model_name='visualcanvas',
            name='grid_width',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Grid horizontal (x) length, where max number of cells is this times grid_length.'),
        ),
    ]
