# Generated by Django 2.0.9 on 2018-11-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0007_auto_20181105_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualcanvas',
            old_name='grid_length',
            new_name='grid_height',
        ),
        migrations.AlterField(
            model_name='visualcanvas',
            name='grid_width',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Grid horizontal (x) length, where max number of cells is this times grid_height.'),
        ),
    ]
