# Generated by Django 2.1.5 on 2019-02-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0008_auto_20181231_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualcelledit',
            name='neighbour_edit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'north'), (1, 'east'), (2, 'south'), (3, 'west')], null=True, verbose_name='Which neighbour, if any, is the source of the edit'),
        ),
    ]
