version: '3.7'

services:
  django: &django
  # container_name: django_test
    links:
      - chrome
      - hub
        # environment:
        # https://docs.djangoproject.com/en/2.2/releases/1.11/
        #   - DJANGO_LIVE_TEST_SERVER_ADDRESS=0.0.0.0:8000
    ports:
      - 1000:6000
      - 8000:8001

  hub:
    image: elgalu/selenium:latest
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false

  chrome:
    image: elgalu/selenium:latest
    depends_on:
      - hub
    ports:
      # VNC: See what's going on by connecting your VNC client to 0.0.0.0:5900
      - 5900:25900
      # noVNC: See what's going on by hitting http://0.0.0.0:6080 in your browser
      #        Important: http://127.0.0.1:6080 works but http://localhost:6080 doesn't
      - 6080:26080
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - NOVNC=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=false
      - GRID=false
      - CHROME=true
      - FIREFOX=false

  firefox:
    image: elgalu/selenium:latest
    depends_on:
      - hub
    ports:
      # VNC: See what's going on by connecting your VNC client to 0.0.0.0:5901
      - 5901:25900
      # noVNC: See what's going on by hitting http://0.0.0.0:6081 in your browser
      - 6081:26080
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - NOVNC=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=false
      - GRID=false
      - CHROME=false
      - FIREFOX=true
